services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eform
    ports:
      - "5432:5432"
    volumes:
      - eform_pg:/var/lib/postgresql/data

volumes:
  eform_pg:
